### ISSUE TITLE
PHP file not working

### ISSUE THREAD

**Issue by nabad600** [markhilton/docker-nginx-pagespeed#3]
Hi, 
I have setup nginx pagespeed without GeoIP, html file working, but php file not working can any one help me.

Thanks

**Comment by markhilton** [comment]
this container does not have PHP installed. You can use this container for PHP-FPM along with Nginx container: https://github.com/markhilton/docker-php-fpm

**Comment by nabad600** [comment]
Hi,
Thanks for your quick reply, I have a install php-fpm container, port 9000 , but don't work, can you help me.

**Comment by markhilton** [comment]
@nabad600 take a look here: https://github.com/markhilton/docker-nginx-php-fpm-example

**Comment by nabad600** [comment]
Hi, 

thaks for your help, can you help me **(docker+nginx+pagespeed+php-fpm)**
